name: Update Rules

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run script
        run: |
          chmod +x scripts/update_rules.sh
          ./scripts/update_rules.sh

      - name: Commit and Push
        run: |
          git config --global user.name "rules-bot"
          git config --global user.email "bot@example.com"

          git add .
          git commit -m "update rules" || echo "no changes"
          git fetch origin
          git reset --hard origin/main

          git add .
          git commit -m "update rules" || echo "no changes"

          git push origin main
