name: Update Rules

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run script
        run: |
          chmod +x scripts/update_rules.sh
          ./scripts/update_rules.sh

      - name: Commit
        run: |
          git config --global user.name "rules-bot"
          git config --global user.email "bot@example.com"
          git add .
          git commit -m "update rules" || echo "no change"
          git push origin HEAD:main --force
